project:
  type: website

website:
  title: "Conciliador Previdenciário"
  reader-mode: true
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/igor-mendonça-93a2b3151/
      - icon: github
        text: Github
        href: https://github.com/jusmendonca

format:
  html:
    theme: 
      light: simplex
      dark: darkly
    css: styles.css

editor: visual

